version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    env_file:
      - .env
    environment:
      - HOST=${HOST}
      - PORT=${BACKEND_PORT}
